version: '3'

services:
  product-service:
    build: ./product-service
    volumes:
      - ./product-service:/usr/src/app
    ports:
      - 5001:80

  website:
    image: php:apache
    volumes:
      - ./webapp:/var/www/html
    ports:
      - 5000:80
    depends_on:
      -  product-service